#include <VLMS/Core/Locale.h>
#include <VLMS/Core/Strings.h>

#include <VLMS/Core/Text.h>

#include <algorithm>
#include <unordered_map>
#include <vector>

namespace VLMS::Core {

namespace {

using StringTable = std::unordered_map<std::string, std::string>;

StringTable arabicStrings()
{
    return {
        {"app.title", "VLMS — نظام إدارة المكتبة الافتراضية"},
        {"nav.members", "الأعضاء"},
        {"nav.catalog", "الفهرس"},
        {"nav.circulation", "الإعارة"},
        {"nav.metrics", "المؤشرات"},
        {"nav.help", "الدليل"},
        {"help.tooltip", "فتح دليل الاستخدام"},
        {"help.notFound", "تعذّر العثور على دليل الاستخدام."},
        {"help.noBrowser", "تعذّر العثور على متصفح لفتح دليل الاستخدام."},
        {"nav.archive", "الأرشيف"},
        {"lang.ar", "العربية"},
        {"lang.fr", "Français"},
        {"lang.en", "English"},
        {"theme.toDark", "الوضع الداكن"},
        {"theme.toLight", "الوضع الفاتح"},
        {"theme.label", "مظهر الواجهة"},
        {"footer.copyright", "© {year} VLMS"},
        // The licence, shown by LicenceDialog when the footer's copyright
        // line is clicked. A deed of gift rather than a software licence:
        // the library owns the solution outright, so there is nothing here
        // restricting what it may do with it. The author is never named in
        // the body, only in the contact block.
        {"licence.title", "الرخصة"},
        {"licence.intro",
         "برنامج VLMS هدية مُهداة إلى المكتبة التي تستعمله. "
         "لم يُطلب عنه أي مقابل، ولا شيء مستحق عليه، والهبة لا رجعة فيها."},
        {"licence.clause.ownership.head", "الحلّ ملك للمكتبة"},
        {"licence.clause.ownership.body",
         "التطبيق، كما هو مُثبَّت هنا، ملك للمكتبة التي تستعمله. وللمكتبة أن تستعمله "
         "وتحتفظ به وتنسخه وتنقله كما تشاء."},
        {"licence.clause.data.head", "بيانات المكتبة ملك لها"},
        {"licence.clause.data.body",
         "الفهرس وبطاقات المنخرطين والمسوحات والصور التي تنشئها المكتبة بهذا التطبيق ملك "
         "للمكتبة وحدها. ولا يدّعي المؤلف أيّ حقّ فيها ولا يحتفظ بنسخة منها."},
        {"licence.clause.warranty.head", "بلا ضمان"},
        {"licence.clause.warranty.body",
         "يُقدَّم التطبيق كما هو. ولا يُقدَّم أيّ وعد بخلوّه من العيوب، أو بملاءمته لغرض بعينه، "
         "أو باستمرار عمله. وعلى المكتبة أن تحتفظ بنسخ احتياطية من بياناتها."},
        {"licence.clause.liability.head", "بلا مسؤولية"},
        {"licence.clause.liability.body",
         "لا يتحمّل المؤلف مسؤولية أيّ خسارة أو ضرر ينشأ عن استعمال هذا التطبيق، سواء كان "
         "الاستعمال خاطئًا أو متعمَّدًا. ويشمل ذلك ضياع البيانات أو تلفها، وتعطّل العمل، وكلّ "
         "ما يترتّب على ذلك."},
        {"licence.clause.support.head", "لا التزام بالدعم"},
        {"licence.clause.support.body",
         "لا يلتزم المؤلف بتقديم دعم أو تدريب أو تحديثات أو إصلاحات. وكلّ عون يُقدَّم هو "
         "امتداد للهبة، لا واجب مستحقّ."},
        {"licence.contact.head", "جهة الاتصال"},
        {"licence.contact.author", "المؤلف: محمد الأمين بن حسين"},
        {"licence.tooltip", "عرض رخصة الاستعمال"},
        {"common.error", "خطأ"},
        {"common.cancel", "إلغاء"},
        // The Ok/Yes/No/Close a librarian reads on a message box or a dialog
        // button box. Qt supplies its own text for those, out of a catalogue
        // this application does not ship, so they stay English unless the code
        // relabels them from here. See localizeButtonBox in UiHelpers.
        {"common.ok", "موافق"},
        {"common.yes", "نعم"},
        {"common.no", "لا"},
        {"common.close", "إغلاق"},
        // The image picker. Qt's own dialog labels these itself, out of the
        // qtbase catalogue; these override it so the wording matches the rest
        // of the application rather than Qt's translator.
        {"file.open", "فتح"},
        {"file.fileName", "اسم الملف:"},
        {"file.fileType", "نوع الملف:"},
        {"file.lookIn", "المجلّد:"},
        {"app.databaseUnavailable",
         "تعذّر فتح قاعدة البيانات. قد تكون أُنشئت بإصدار أحدث من البرنامج. "
                        "يرجى تحديث VLMS أو الاتصال بمسؤول النظام."},
        {"common.emDash", "—"},
        {"pager.previous", "السابقة"},
        {"pager.next", "التالية"},
        {"pager.first", "الأولى"},
        {"pager.last", "الأخيرة"},
        {"pager.all", "الكل"},
        {"pager.range", "{from}–{to} من {total}"},
        {"pager.page", "صفحة"},
        {"page.members.title", "الأعضاء"},
        {"page.members.body",
         "تسجيل الأعضاء، إدارة الصور وبطاقات الهوية، تحديث بيانات الاتصال، "
                        "تغيير الحالة (نشط، غير نشط)، إضافة ملاحظات، "
                        "وإدارة الإعارات والإرجاع."},
        {"page.catalog.title", "الفهرس"},
        {"page.catalog.body",
         "إضافة وتعديل الكتب، إدارة التصنيفات، إرفاق صور الأغلفة، وحذف العناوين."},
        {"page.circulation.title", "الإعارة"},
        {"page.circulation.body",
         "إعارة الكتب للأعضاء ومعالجة الإرجاعات على مكتب الاستقبال."},
        {"page.metrics.title", "المؤشرات"},
        {"page.metrics.body",
         "عرض حركة المكتبة والنشاط: ملخصات يومية وأسبوعية وشهرية."},
        {"page.archive.title", "الأرشيف"},
        {"page.archive.body", "الأعضاء والكتب والنسخ والإعارات المؤرشفة."},
        {"archive.type.members", "الأعضاء"},
        {"archive.type.books", "الكتب"},
        {"archive.type.copies", "النسخ"},
        {"archive.type.loans", "الإعارات"},
        {"archive.searchPlaceholder", "البحث في الأرشيف…"},
        {"archive.col.number", "الرقم"},
        {"archive.col.name", "الاسم"},
        {"archive.col.city", "المدينة"},
        {"archive.col.status", "الحالة"},
        {"archive.col.title", "العنوان"},
        {"archive.col.author", "المؤلف"},
        {"archive.col.copies", "النسخ المؤرشفة"},
        {"archive.col.localId", "الرقم المحلي"},
        {"archive.col.source", "المصدر"},
        {"archive.col.member", "العضو"},
        {"archive.col.copy", "النسخة / العنوان"},
        {"archive.col.returnedAt", "تاريخ الإرجاع"},
        {"archive.col.archivedAt", "تاريخ الأرشفة"},
        {"archive.col.notes", "ملاحظات النسخة"},
        {"archive.col.loans", "الإعارات"},
        {"archive.restore", "استرجاع"},
        {"archive.restoreConfirm", "إعادة هذا السجل من الأرشيف؟"},
        {"archive.purge", "حذف نهائي"},
        {"archive.purgeConfirmMember",
         "حذف هذا العضو نهائيًا؟ لا يمكن التراجع عن هذه العملية."},
        {"archive.purgeConfirmBook",
         "حذف هذا الكتاب نهائيًا؟ لا يمكن التراجع عن هذه العملية."},
        {"archive.purgeConfirmCopy",
         "حذف هذه النسخة نهائيًا؟ سيعود رقمها المحلي متاحًا. لا يمكن التراجع عن هذه العملية."},
        {"archive.purgeConfirmLoan",
         "حذف هذه الإعارة نهائيًا؟ لا يمكن التراجع عن هذه العملية."},
        {"bulk.confirm", "{noun} ({count}): هل تريد {verb}؟"},
        {"bulk.confirmOne", "«{label}»: هل تريد {verb}؟"},
        {"bulk.blockedIntro", "{noun}: {blocked} من أصل {count} لا تقبل {passive}:"},
        {"bulk.andMore", "…و{count} أخرى"},
        {"bulk.confirmRest", "هل تريد {verb} للبقية ({count})؟"},
        {"bulk.summary", "{passive} — تمّ: {done}، تعذّر: {failed}. {reason}"},
        {"bulk.noun.books", "الكتب"},
        {"bulk.noun.members", "الأعضاء"},
        {"bulk.noun.loans", "الإعارات"},
        {"bulk.noun.copies", "النسخ"},
        {"bulk.verb.archive", "الأرشفة"},
        {"bulk.passive.archive", "الأرشفة"},
        {"bulk.verb.restore", "الاسترجاع"},
        {"bulk.passive.restore", "الاسترجاع"},
        {"bulk.verb.purge", "الحذف النهائي"},
        {"bulk.passive.purge", "الحذف النهائي"},
        {"bulk.verb.remove", "الإزالة"},
        {"bulk.passive.remove", "الإزالة"},
        {"archive.loans", "الإعارات"},
        {"archive.loanHistoryTitle", "سجل الإعارات — {name}"},
        {"archive.loanHistoryEmpty", "لا توجد إعارات."},
        {"archive.reuse", "إعادة استعمال الرقم المحلي"},
        {"archive.reuse.title", "اختيار الكتاب"},
        {"archive.reuse.prompt", "الكتاب الذي سيأخذ الرقم {number}:"},
        {"archive.reuse.search", "البحث عن كتاب…"},
        {"archive.reuse.newBook", "كتاب جديد"},
        {"metrics.refresh", "تحديث"},
        {"metrics.section.overview", "نظرة عامة على المكتبة"},
        {"metrics.section.members", "الأعضاء"},
        {"metrics.section.circulation", "الإعارة"},
        {"metrics.section.activity", "النشاط"},
        {"metrics.section.categories", "أبرز التصنيفات"},
        {"metrics.bookTitles", "عناوين الكتب"},
        {"metrics.totalCopies", "إجمالي النسخ"},
        {"metrics.availableCopies", "نسخ متاحة"},
        {"metrics.onLoanCopies", "نسخ مُعارة"},
        {"metrics.totalMembers", "إجمالي الأعضاء"},
        {"metrics.membersActive", "نشطون"},
        {"metrics.membersNonActive", "غير نشطين"},
        {"metrics.openLoans", "إعارات مفتوحة"},
        {"metrics.overdueLoans", "إعارات متأخرة"},
        {"metrics.returnedLoans", "إعارات مُرجَعة"},
        {"metrics.period.today", "اليوم"},
        {"metrics.period.week", "آخر 7 أيام"},
        {"metrics.period.month", "هذا الشهر"},
        {"metrics.col.period", "الفترة"},
        {"metrics.col.checkouts", "إعارات"},
        {"metrics.col.returns", "إرجاعات"},
        {"metrics.col.newMembers", "أعضاء جدد"},
        {"metrics.col.category", "التصنيف"},
        {"metrics.col.books", "الكتب"},
        {"metrics.noCategories", "لا توجد تصنيفات بعد."},
        {"members.searchPlaceholder",
         "البحث بالرقم أو الاسم أو الهاتف أو المدينة…"},
        {"members.addMember", "إضافة عضو"},
        {"members.loans", "الإعارات"},
        {"members.loanHistoryTitle", "سجل الإعارات — {name}"},
        {"members.loanHistoryEmpty", "لم يستعر هذا العضو أي كتاب بعد."},
        {"members.edit", "تعديل"},
        {"members.delete", "حذف"},
        {"members.allStatuses", "كل الحالات"},
        {"members.allSexes", "كلا الجنسين"},
        {"members.allYears", "كل سنوات التسجيل"},
        {"circulation.allLoanYears", "كل سنوات الإعارة"},
        {"members.allAgeGroups", "كل الفئات العمرية"},
        {"members.allCities", "كل المدن"},
        {"members.noPhoto", "لا توجد صورة"},
        {"members.hasIdImage", "نعم"},
        {"members.col.number", "الرقم"},
        {"members.col.name", "الاسم"},
        {"members.col.phone", "الهاتف"},
        {"members.col.city", "المدينة"},
        {"members.col.status", "الحالة"},
        {"members.col.loans", "الإعارات"},
        {"members.editMember", "تعديل العضو"},
        {"members.deleteMember", "حذف العضو"},
        {"members.selectMemberFirst", "يرجى اختيار عضو أولاً."},
        {"members.deleteConfirm", "إزالة العضو المحدد؟"},
        {"members.goToLoans", "الذهاب إلى الإعارة"},
        {"members.deleteBlockedByLoans",
         "لا يزال لدى هذا العضو كتب معارة. يرجى تسجيل إرجاعها أولاً "
                        "ثم إزالة العضو."},
        {"member.status.active", "نشط"},
        {"member.status.non_active", "غير نشط"},
        {"member.addTitle", "إضافة عضو"},
        {"member.editTitle", "تعديل عضو"},
        {"member.field.number", "رقم العضوية"},
        {"member.field.numberHint", "يُعيَّن تلقائياً ولا يمكن تغييره"},
        {"member.field.firstName", "الاسم"},
        {"member.field.lastName", "اللقب"},
        {"member.field.sex", "الجنس"},
        {"member.sex.male", "ذكر"},
        {"member.sex.female", "أنثى"},
        {"member.field.occupation", "المهنة"},
        {"member.field.ageGroup", "الفئة العمرية"},
        {"member.ageGroup.youth", "شباب"},
        {"member.ageGroup.adult", "كهول"},
        {"member.field.dateOfBirth", "تاريخ الميلاد"},
        {"member.field.registeredAt", "تاريخ التسجيل"},
        {"member.field.email", "البريد الإلكتروني"},
        {"member.field.phone", "الهاتف"},
        {"member.field.address", "العنوان"},
        {"member.field.city", "المدينة"},
        {"member.field.status", "الحالة"},
        {"member.field.activeUntil", "نشط حتى"},
        {"member.field.notes", "ملاحظات"},
        {"member.field.photo", "الصورة"},
        {"member.field.idImage", "صورة الهوية"},
        {"member.choosePhoto", "اختيار صورة…"},
        {"member.chooseIdImage", "اختيار صورة الهوية…"},
        {"member.selectPhoto", "اختيار صورة العضو"},
        {"member.selectIdImage", "اختيار صورة الهوية"},
        {"member.imageFilter", "صور (*.png *.jpg *.jpeg *.webp *.bmp)"},
        {"member.viewPhoto", "عرض الصورة"},
        {"member.viewIdImage", "عرض صورة الهوية"},
        {"imageViewer.change", "تغيير…"},
        {"imageViewer.remove", "إزالة"},
        {"imageViewer.close", "إغلاق"},
        {"member.validation", "التحقق"},
        {"member.nameRequired", "الاسم واللقب مطلوبان."},
        {"member.emailInvalid", "البريد الإلكتروني غير صالح. مثال: name@example.org"},
        {"member.dateOfBirthRequired", "أدخل تاريخ الميلاد."},
        {"member.dateOfBirthInvalid",
         "تاريخ الميلاد غير صالح. استعمل الشكل سنة-شهر-يوم، مثال: \u200E1990-05-12\u200E."},
        {"member.dateOfBirthInFuture", "تاريخ الميلاد لا يمكن أن يكون لاحقاً لتاريخ اليوم."},
        {"circulation.searchPlaceholder",
         "البحث بالعضو أو العنوان أو رقم النسخة…"},
        {"circulation.checkout", "إعارة"},
        {"circulation.extend", "تمديد"},
        {"circulation.return", "إرجاع"},
        {"circulation.filter.open", "مفتوحة"},
        {"circulation.filter.overdue", "متأخرة"},
        {"circulation.filter.returned", "مُرجَعة"},
        {"circulation.filter.all", "الكل"},
        {"circulation.col.member", "العضو"},
        {"circulation.col.number", "الرقم"},
        {"circulation.col.title", "العنوان"},
        {"circulation.col.borrowed", "الإعارة"},
        {"circulation.col.due", "الاستحقاق"},
        {"circulation.col.status", "الحالة"},
        {"circulation.status.open", "مفتوحة"},
        {"circulation.status.overdue", "متأخرة"},
        {"circulation.status.returned", "مُرجَعة"},
        {"circulation.selectLoanFirst", "يرجى اختيار إعارة أولاً."},
        {"circulation.alreadyReturned", "هذه الإعارة مُرجَعة مسبقاً."},
        {"circulation.delete", "حذف"},
        {"circulation.archiveLoan", "نقل هذه الإعارة المُرجعة إلى الأرشيف؟"},
        {"loan.checkoutTitle", "إعارة كتاب"},
        {"loan.returnTitle", "إرجاع كتاب"},
        {"loan.extendTitle", "تمديد الإعارة"},
        {"loan.returnSummary",
         "{member} ({number}) — {title} [{copy}]"},
        {"loan.field.memberSearch", "بحث عن عضو"},
        {"loan.field.member", "العضو"},
        {"loan.field.copySearch", "بحث عن نسخة"},
        {"loan.field.copy", "النسخة"},
        {"loan.field.borrowedAt", "تاريخ الإعارة"},
        {"loan.field.dueAt", "تاريخ الاستحقاق"},
        {"loan.field.currentDueAt", "تاريخ الاستحقاق الحالي"},
        {"loan.field.newDueAt", "تاريخ الاستحقاق الجديد"},
        {"loan.field.returnedAt", "تاريخ الإرجاع"},
        {"loan.field.notes", "ملاحظات"},
        {"loan.memberSearchHint", "رقم العضوية أو الاسم…"},
        {"loan.copySearchHint", "العنوان أو رقم النسخة أو ISBN…"},
        {"loan.noMembers", "(لا يوجد أعضاء نشطون)"},
        {"loan.noCopies", "(لا توجد نسخ متاحة)"},
        {"loan.validation", "التحقق"},
        {"loan.memberRequired", "يرجى اختيار عضو نشط."},
        {"loan.copyRequired", "يرجى اختيار نسخة متاحة."},
        {"loan.dueBeforeBorrow",
         "تاريخ الاستحقاق لا يمكن أن يكون قبل تاريخ الإعارة."},
        {"loan.extendInvalid",
         "يجب أن يكون تاريخ الاستحقاق الجديد بعد التاريخ الحالي."},
        {"loan.returnAfterToday",
         "لا يمكن أن يكون تاريخ الإرجاع في المستقبل."},
        {"catalog.searchPlaceholder",
         "البحث بالعنوان أو المؤلف أو ISBN أو الرقم المحلي…"},
        {"catalog.withCover", "مع غلاف"},
        {"catalog.withoutCover", "بدون غلاف"},
        {"catalog.allCovers", "الكل"},
        {"catalog.addBook", "إضافة كتاب"},
        {"catalog.edit", "تعديل"},
        {"catalog.delete", "حذف"},
        {"catalog.categories", "التصنيفات…"},
        {"catalog.loans", "الإعارات"},
        {"catalog.loanHistoryTitle", "سجل الإعارات — {name}"},
        {"catalog.loanHistoryEmpty", "لم يُعَر هذا الكتاب بعد."},
        {"catalog.allCategories", "كل التصنيفات"},
        {"catalog.allLanguages", "كل اللغات"},
        {"catalog.noCover", "لا يوجد غلاف"},
        {"catalog.col.title", "العنوان"},
        {"catalog.col.author", "المؤلف"},
        {"catalog.col.category", "التصنيف"},
        {"catalog.col.localNumber", "الرقم المحلي"},
        {"catalog.col.copies", "النسخ"},
        {"catalog.col.available", "المتاح"},
        {"catalog.editBook", "تعديل الكتاب"},
        {"catalog.deleteBook", "حذف الكتاب"},
        {"catalog.selectBookFirst", "يرجى اختيار كتاب أولاً."},
        {"catalog.deleteConfirm", "نقل هذا الكتاب وكل نسخه إلى الأرشيف؟"},
        {"book.language.ar", "عربي"},
        {"book.language.fr", "فرنسي"},
        {"book.language.en", "إنجليزي"},
        {"book.language.es", "إسباني"},
        {"book.language.de", "ألماني"},
        {"book.language.it", "إيطالي"},
        {"book.language.tr", "تركي"},
        {"book.language.pt", "برتغالي"},
        {"book.language.ru", "روسي"},
        {"book.language.zh", "صيني"},
        {"book.language.other", "أخرى…"},
        {"book.addTitle", "إضافة كتاب"},
        {"book.editTitle", "تعديل كتاب"},
        {"book.field.title", "العنوان"},
        {"book.field.author", "المؤلف"},
        {"book.field.publisher", "الناشر"},
        {"book.field.category", "التصنيف"},
        {"book.field.isbn", "ISBN"},
        {"book.field.publicationDate", "تاريخ النشر"},
        {"book.field.publicationDateHint", "مثال: 2020 أو \u200E2020-05-12\u200E"},
        {"book.field.place", "مكان النشر"},
        {"book.field.pages", "الصفحات"},
        {"book.field.dimensions", "الأبعاد"},
        {"book.field.language", "اللغة"},
        {"book.field.languageOtherHint", "حدد اللغة"},
        {"book.field.cover", "الغلاف"},
        {"book.field.description", "الوصف"},
        {"book.noneCategory", "(بدون)"},
        {"book.tab.book", "الكتاب"},
        {"book.tab.copies", "النسخ"},
        {"book.copy.localId", "الرقم المحلي"},
        {"book.copy.globalId", "الرقم العام"},
        {"book.copy.source", "الرصيد"},
        {"book.copy.source.arabic", "عربي"},
        {"book.copy.source.foreign", "أجنبي"},
        {"book.copy.centralId", "الرقم المركزي"},
        {"book.copy.classification", "رمز التصنيف"},
        {"book.copy.subject", "الموضوع"},
        {"book.copy.indexCode", "رمز الفهرسة"},
        {"book.copy.location", "المكان"},
        {"book.copy.inventoryStatus", "الجرد"},
        {"book.copy.compensation", "التعويض"},
        {"book.copy.notes", "ملاحظات"},
        {"book.copy.status", "الحالة"},
        {"book.copy.statusOnLoan", "مُعارة"},
        {"book.copy.statusAvailable", "متاحة"},
        {"book.copy.add", "إضافة نسخة"},
        {"book.copy.remove", "حذف النسخة"},
        {"book.copy.selectFirst", "يرجى اختيار نسخة أولاً."},
        {"book.copy.identifierRequired",
         "كل نسخة تحتاج رقماً محلياً ورقماً عاماً."},
        {"book.copy.duplicateIdentifier",
         "الرقم ‏{identifier}‏ مستعمل مرتين في هذه القائمة."},
        {"book.copy.cannotRemoveOnLoan",
         "لا يمكن حذف نسخة مُعارة حالياً."},
        {"book.copy.numberReserved", "هذا الرقم محجوز إلى أن يُحفظ الكتاب."},
        {"book.chooseCover", "اختيار صورة الغلاف…"},
        {"book.selectCover", "اختيار صورة الغلاف"},
        {"book.coverFilter", "صور (*.png *.jpg *.jpeg *.webp *.bmp)"},
        {"book.validation", "التحقق"},
        {"book.titleRequired", "العنوان مطلوب."},
        {"book.languageRequired", "اللغة مطلوبة."},
        {"ocr.title", "من صورة"},
        {"ocr.readFromImage", "من صورة"},
        {"ocr.readFromImageTip",
         "استخراج النص من صورة عبر Tesseract"},
        {"ocr.languageInUse", "اللغة المستخدمة: {languages}"},
        {"ocr.imageFilter",
         "صور (*.png *.jpg *.jpeg *.webp *.bmp *.tif *.tiff)"},
        {"ocr.selectImage", "اختيار صورة للقراءة"},
        {"ocr.working", "جارٍ قراءة النص من الصورة…"},
        {"ocr.cancelling", "جارٍ الإلغاء…"},
        {"ocr.unavailable",
         "محرك التعرف على النص غير متوفر. ثبّت libtesseract وحزم اللغات."},
        {"ocr.imageMissing", "تعذّر فتح الصورة المحددة."},
        {"ocr.startFailed", "تعذّر تشغيل محرك التعرف على النص."},
        {"ocr.failed", "فشل التعرف على النص."},
        {"ocr.empty", "لم يُعثر على نص في الصورة."},
        {"category.manageTitle", "إدارة التصنيفات"},
        {"category.col.code", "الرمز"},
        {"category.col.label", "التسمية"},
        {"category.col.books", "الكتب"},
        {"category.add", "إضافة"},
        {"category.edit", "تعديل"},
        {"category.delete", "حذف"},
        {"category.addTitle", "إضافة تصنيف"},
        {"category.editTitle", "تعديل تصنيف"},
        {"category.deleteTitle", "حذف تصنيف"},
        {"category.field.code", "الرمز:"},
        {"category.field.label", "التسمية:"},
        {"category.selectFirst", "يرجى اختيار تصنيف أولاً."},
        {"category.deleteConfirm",
         "حذف هذا التصنيف؟ لا يمكن حذف التصنيفات التي تحتوي على كتب."},
        {"copy.note.wasIndexedAs", "كان مفهرسًا تحت الرقم {number}"},
        {"copy.note.newIndexedAs", "أعيدت فهرسته تحت الرقم {number}"},
        {"error.sql", "حدث خطأ في قاعدة البيانات."},
        {"error.book.notFound", "هذا الكتاب لم يعد موجوداً."},
        {"error.book.titleRequired", "العنوان مطلوب."},
        {"error.book.languageRequired", "اللغة مطلوبة."},
        {"error.book.minCopies", "يحتاج الكتاب إلى نسخة واحدة على الأقل."},
        {"error.book.hasActiveLoans", "لا يمكن حذف كتاب عليه إعارات قائمة."},
        {"error.book.hasCopies", "أزل نسخ هذا الكتاب المؤرشفة قبل حذف العنوان نهائيًا."},
        {"error.book.duplicateArchived", "هذا الكتاب موجود في الأرشيف؛ استرجعه من هناك."},
        {"error.book.notArchived", "هذا الكتاب ليس في الأرشيف."},
        {"error.cover.emptyPath", "مسار صورة الغلاف فارغ."},
        {"error.cover.missingFile", "ملف صورة الغلاف غير موجود."},
        {"error.cover.copyFailed", "تعذّر نسخ صورة الغلاف."},
        {"error.category.codeRequired", "رمز التصنيف مطلوب."},
        {"error.category.notFound", "هذا التصنيف لم يعد موجوداً."},
        {"error.category.hasBooks", "لا يمكن حذف تصنيف يحتوي على كتب."},
        {"error.copy.nextNumber", "تعذّر تحديد رقم النسخة التالي."},
        {"error.copy.idsRequired", "كل نسخة تحتاج رقماً محلياً ورقماً عاماً."},
        {"error.copy.duplicateGlobalInList", "رقم النسخة «{detail}» مستخدم مرتين."},
        {"error.copy.duplicateLocalInList", "الرقم المحلي «{detail}» مستخدم مرتين في نفس الرصيد."},
        {"error.copy.onLoan", "لا يمكن حذف نسخ مُعارة حالياً."},
        {"error.copy.duplicateGlobal",
         "رقم النسخة «{detail}» يخص نسخة أخرى."},
        {"error.copy.duplicateLocal", "الرقم المحلي «{detail}» يخص نسخة أخرى في نفس الرصيد."},
        {"error.copy.notFound", "هذه النسخة لم تعد موجودة."},
        {"error.copy.notArchived", "هذه النسخة ليست في الأرشيف."},
        {"error.copy.hasHistory", "هذه النسخة أُعيرت من قبل؛ احذف إعاراتها من الأرشيف أولًا."},
        {"error.copy.bookMissing", "الكتاب الأصلي لهذه النسخة لم يعد موجودًا."},
        {"error.copy.numberHeldByArchived",
         "الرقم «{detail}» محجوز لنسخة مؤرشفة؛ انقله من الأرشيف ← إعادة استعمال الرقم المحلي."},
        {"error.copy.reuseStale", "النسخة المؤرشفة لم تعد تحمل هذا الرقم."},
        {"error.copy.sourceMismatch", "لغة هذا الكتاب لا تناسب مصدر الرقم."},
        {"error.member.notFound", "هذا العضو لم يعد موجوداً."},
        {"error.member.namesRequired", "الاسم الأول واللقب مطلوبان."},
        {"error.member.invalidSex", "جنس العضو غير صالح."},
        {"error.member.invalidDob", "تاريخ الميلاد يجب أن يكون تاريخاً حقيقياً بصيغة سنة-شهر-يوم."},
        {"error.member.dobInFuture", "تاريخ الميلاد لا يمكن أن يكون لاحقاً لتاريخ اليوم."},
        {"error.member.invalidEmail",
         "البريد يجب أن يبدو مثل name@example.org، أو يُترك فارغاً."},
        {"error.member.invalidStatus", "حالة العضو غير صالحة."},
        {"error.member.archiveHasLoans", "لا يمكن أرشفة عضو عليه إعارات قائمة."},
        {"error.member.deleteHasLoans", "لا يمكن حذف عضو عليه إعارات قائمة."},
        {"error.member.hasHistory",
         "لهذا العضو سجل إعارة ولا يمكن حذفه. أرشفه بدلاً من ذلك."},
        {"error.member.notArchived", "هذا العضو ليس في الأرشيف."},
        {"error.image.emptyPath", "مسار الصورة فارغ."},
        {"error.image.missingFile", "ملف الصورة غير موجود."},
        {"error.image.copyFailed", "تعذّر نسخ الصورة."},
        {"error.loan.notFound", "هذه الإعارة لم تعد موجودة."},
        {"error.loan.alreadyReturned", "هذه الإعارة مُرجعة مسبقاً."},
        {"error.loan.dueRequired", "تاريخ الاستحقاق مطلوب."},
        {"error.loan.memberRequired", "العضو مطلوب."},
        {"error.loan.copyRequired", "نسخة الكتاب مطلوبة."},
        {"error.loan.cannotReturn", "تعذّر إرجاع الإعارة."},
        {"error.loan.cannotExtend", "تعذّر تمديد الإعارة."},
        {"error.loan.memberArchived", "هذا العضو مؤرشف ولا يمكنه الاستعارة."},
        {"error.loan.memberInactive", "الأعضاء النشطون فقط يمكنهم الاستعارة."},
        {"error.loan.copyNotFound", "نسخة الكتاب غير موجودة."},
        {"error.loan.copyOnLoan", "هذه النسخة مُعارة حالياً."},
        {"error.loan.borrowUnreadable", "تاريخ الإعارة يجب أن يكون تاريخاً حقيقياً بصيغة سنة-شهر-يوم."},
        {"error.loan.dueUnreadable", "تاريخ الاستحقاق يجب أن يكون تاريخاً حقيقياً بصيغة سنة-شهر-يوم."},
        {"error.loan.dueNotAfterBorrow",
         "تاريخ الاستحقاق يجب أن يكون بعد تاريخ الإعارة."},
        {"error.loan.borrowInFuture", "تاريخ الإعارة لا يمكن أن يكون في المستقبل."},
        {"error.loan.returnUnreadable", "تاريخ الإرجاع يجب أن يكون تاريخاً حقيقياً بصيغة سنة-شهر-يوم."},
        {"error.loan.storedBorrowUnreadable",
         "تاريخ إعارة هذه العملية غير قابل للقراءة، لذلك لا يمكن التحقق من تاريخ الإرجاع. صحّح الإعارة أولاً."},
        {"error.loan.returnBeforeBorrow",
         "تاريخ الإرجاع لا يمكن أن يكون قبل تاريخ الإعارة."},
        {"error.loan.returnInFuture", "تاريخ الإرجاع لا يمكن أن يكون في المستقبل."},
        {"error.loan.storedDueUnreadable",
         "تاريخ استحقاق هذه الإعارة غير قابل للقراءة، لذلك لا يمكن تمديدها. صحّح الإعارة أولاً."},
        {"error.loan.extendNotAfter",
         "تاريخ الاستحقاق الجديد يجب أن يكون بعد التاريخ الحالي."},
        {"error.loan.extendInPast",
         "تاريخ الاستحقاق الجديد لا يمكن أن يكون في الماضي."},
        {"error.loan.archiveOpen", "لا يمكن أرشفة إعارة لم تُرجع بعد."},
        {"error.loan.notArchived", "هذه الإعارة ليست في الأرشيف."},
        {"error.loan.copyArchived", "هذه النسخة مؤرشفة ولا يمكن إعارتها."},
    };
}

StringTable frenchStrings()
{
    return {
        {"app.title", "VLMS — Système de gestion de bibliothèque virtuelle"},
        {"nav.members", "Adhérents"},
        {"nav.catalog", "Catalogue"},
        {"nav.circulation", "Circulation"},
        {"nav.metrics", "Indicateurs"},
        {"nav.help", "Aide"},
        {"help.tooltip", "Ouvrir le manuel d'utilisation"},
        {"help.notFound", "Le manuel d'utilisation est introuvable."},
        {"help.noBrowser", "Aucun navigateur n'a été trouvé pour ouvrir le manuel d'utilisation."},
        {"nav.archive", "Archives"},
        {"lang.ar", "العربية"},
        {"lang.fr", "Français"},
        {"lang.en", "English"},
        {"theme.toDark", "Mode sombre"},
        {"theme.toLight", "Mode clair"},
        {"theme.label", "Thème de l'interface"},
        {"footer.copyright", "© {year} VLMS"},
        {"licence.title", "Licence"},
        {"licence.intro",
         "VLMS est offert en don à la Bibliothèque qui l'utilise. Rien n'a été facturé, "
         "rien n'est dû, et ce don est irrévocable."},
        {"licence.clause.ownership.head", "La solution appartient à la Bibliothèque"},
        {"licence.clause.ownership.body",
         "L'application, telle qu'elle est installée ici, appartient à la Bibliothèque "
         "qui l'utilise. La Bibliothèque peut l'utiliser, la conserver, la copier "
         "et la transmettre comme elle l'entend."},
        {"licence.clause.data.head", "Les données de la Bibliothèque lui appartiennent"},
        {"licence.clause.data.body",
         "Le catalogue, les fiches des adhérents, les numérisations et les photographies que "
         "la Bibliothèque crée avec cette application lui appartiennent exclusivement. "
         "L'auteur n'y revendique aucun droit et n'en conserve aucune copie."},
        {"licence.clause.warranty.head", "Aucune garantie"},
        {"licence.clause.warranty.body",
         "L'application est fournie en l'état. Aucune promesse n'est faite quant à l'absence "
         "de défauts, à l'adéquation à un usage particulier, ou à la continuité de son "
         "fonctionnement. La Bibliothèque doit conserver ses propres sauvegardes."},
        {"licence.clause.liability.head", "Aucune responsabilité"},
        {"licence.clause.liability.body",
         "L'auteur n'est pas responsable des pertes ou dommages résultant de l'utilisation "
         "de cette application, que cette utilisation ait été erronée ou délibérée. Cela "
         "comprend les données perdues ou corrompues, le travail interrompu, et toute "
         "conséquence de l'un ou l'autre."},
        {"licence.clause.support.head", "Aucune obligation d'assistance"},
        {"licence.clause.support.body",
         "L'auteur n'est tenu à aucune assistance, formation, mise à jour ni réparation. "
         "Toute aide apportée prolonge le don ; elle n'est pas une obligation."},
        {"licence.contact.head", "Contact"},
        {"licence.contact.author", "L'auteur : Mohamed Lamine Ben Hassine"},
        {"licence.tooltip", "Afficher la licence"},
        {"common.error", "Erreur"},
        {"common.cancel", "Annuler"},
        {"common.ok", "OK"},
        {"common.yes", "Oui"},
        {"common.no", "Non"},
        {"common.close", "Fermer"},
        {"file.open", "Ouvrir"},
        {"file.fileName", "Nom du fichier :"},
        {"file.fileType", "Type de fichier :"},
        {"file.lookIn", "Dossier :"},
        {"app.databaseUnavailable",
         "Impossible d'ouvrir la base de données. Elle a peut-être été créée par "
                        "une version plus récente du logiciel. Mettez VLMS à jour ou "
                        "contactez l'administrateur."},
        {"common.emDash", "—"},
        {"pager.previous", "Précédent"},
        {"pager.next", "Suivant"},
        {"pager.first", "Premier"},
        {"pager.last", "Dernier"},
        {"pager.all", "Tous"},
        {"pager.range", "{from}–{to} sur {total}"},
        {"pager.page", "page"},
        {"page.members.title", "Adhérents"},
        {"page.members.body",
         "Inscrire les adhérents, gérer les photos et pièces d'identité, mettre à jour "
                        "les coordonnées, changer le statut (actif, inactif), "
                        "ajouter des notes et gérer les prêts et retours."},
        {"page.catalog.title", "Catalogue"},
        {"page.catalog.body",
         "Ajouter et modifier des ouvrages, gérer les catégories, joindre des couvertures "
                        "et supprimer des titres."},
        {"page.circulation.title", "Circulation"},
        {"page.circulation.body",
         "Prêter des ouvrages aux adhérents et traiter les retours au comptoir."},
        {"page.metrics.title", "Indicateurs"},
        {"page.metrics.body",
         "Consulter la fréquentation et l'activité : résumés quotidiens, hebdomadaires "
                        "et mensuels."},
        {"page.archive.title", "Archives"},
        {"page.archive.body", "Adhérents, ouvrages, exemplaires et prêts archivés."},
        {"archive.type.members", "Adhérents"},
        {"archive.type.books", "Ouvrages"},
        {"archive.type.copies", "Exemplaires"},
        {"archive.type.loans", "Prêts"},
        {"archive.searchPlaceholder", "Rechercher dans les archives…"},
        {"archive.col.number", "Numéro"},
        {"archive.col.name", "Nom"},
        {"archive.col.city", "Ville"},
        {"archive.col.status", "Statut"},
        {"archive.col.title", "Titre"},
        {"archive.col.author", "Auteur"},
        {"archive.col.copies", "Exemplaires archivés"},
        {"archive.col.localId", "N° local"},
        {"archive.col.source", "Source"},
        {"archive.col.member", "Adhérent"},
        {"archive.col.copy", "Exemplaire / titre"},
        {"archive.col.returnedAt", "Rendu le"},
        {"archive.col.archivedAt", "Archivé le"},
        {"archive.col.notes", "Notes de l'exemplaire"},
        {"archive.col.loans", "Prêts"},
        {"archive.restore", "Restaurer"},
        {"archive.restoreConfirm", "Restaurer cet élément depuis les archives ?"},
        {"archive.purge", "Suppression définitive"},
        {"archive.purgeConfirmMember",
         "Supprimer définitivement cet adhérent ? Cette opération est irréversible."},
        {"archive.purgeConfirmBook",
         "Supprimer définitivement cet ouvrage ? Cette opération est irréversible."},
        {"archive.purgeConfirmCopy",
         "Supprimer définitivement cet exemplaire ? Son numéro local redevient disponible. "
         "Cette opération est irréversible."},
        {"archive.purgeConfirmLoan",
         "Supprimer définitivement ce prêt ? Cette opération est irréversible."},
        {"bulk.confirm", "{verb} {count} {noun} ?"},
        {"bulk.confirmOne", "{verb} « {label} » ?"},
        {"bulk.blockedIntro", "{blocked} sur {count} {noun} ne peuvent pas être {passive} :"},
        {"bulk.andMore", "…et {count} de plus"},
        {"bulk.confirmRest", "{verb} les {count} autres ?"},
        {"bulk.summary", "{done} {passive}, {failed} échec : {reason}"},
        {"bulk.noun.books", "ouvrages"},
        {"bulk.noun.members", "adhérents"},
        {"bulk.noun.loans", "prêts"},
        {"bulk.noun.copies", "exemplaires"},
        {"bulk.verb.archive", "Archiver"},
        {"bulk.passive.archive", "archivés"},
        {"bulk.verb.restore", "Restaurer"},
        {"bulk.passive.restore", "restaurés"},
        {"bulk.verb.purge", "Supprimer définitivement"},
        {"bulk.passive.purge", "supprimés"},
        {"bulk.verb.remove", "Retirer"},
        {"bulk.passive.remove", "retirés"},
        {"archive.loans", "Prêts"},
        {"archive.loanHistoryTitle", "Historique des prêts — {name}"},
        {"archive.loanHistoryEmpty", "Aucun prêt."},
        {"archive.reuse", "Réutiliser le n° local"},
        {"archive.reuse.title", "Choisir l'ouvrage"},
        {"archive.reuse.prompt", "Ouvrage qui recevra le n° {number} :"},
        {"archive.reuse.search", "Rechercher un ouvrage…"},
        {"archive.reuse.newBook", "Nouvel ouvrage"},
        {"metrics.refresh", "Actualiser"},
        {"metrics.section.overview", "Vue d'ensemble"},
        {"metrics.section.members", "Adhérents"},
        {"metrics.section.circulation", "Circulation"},
        {"metrics.section.activity", "Activité"},
        {"metrics.section.categories", "Principales catégories"},
        {"metrics.bookTitles", "Titres"},
        {"metrics.totalCopies", "Exemplaires au total"},
        {"metrics.availableCopies", "Exemplaires disponibles"},
        {"metrics.onLoanCopies", "Exemplaires prêtés"},
        {"metrics.totalMembers", "Adhérents au total"},
        {"metrics.membersActive", "Actifs"},
        {"metrics.membersNonActive", "Inactifs"},
        {"metrics.openLoans", "Prêts ouverts"},
        {"metrics.overdueLoans", "Prêts en retard"},
        {"metrics.returnedLoans", "Prêts retournés"},
        {"metrics.period.today", "Aujourd'hui"},
        {"metrics.period.week", "Sur 7 jours"},
        {"metrics.period.month", "Ce mois-ci"},
        {"metrics.col.period", "Période"},
        {"metrics.col.checkouts", "Prêts"},
        {"metrics.col.returns", "Retours"},
        {"metrics.col.newMembers", "Inscriptions"},
        {"metrics.col.category", "Catégorie"},
        {"metrics.col.books", "Ouvrages"},
        {"metrics.noCategories", "Aucune catégorie pour l'instant."},
        {"members.searchPlaceholder",
         "Rechercher par numéro, nom, téléphone ou ville…"},
        {"members.addMember", "Ajouter un adhérent"},
        {"members.loans", "Prêts"},
        {"members.loanHistoryTitle", "Historique des prêts — {name}"},
        {"members.loanHistoryEmpty", "Cet adhérent n'a encore rien emprunté."},
        {"members.edit", "Modifier"},
        {"members.delete", "Supprimer"},
        {"members.allStatuses", "Tous les statuts"},
        {"members.allSexes", "Tous les sexes"},
        {"members.allYears", "Toutes les années"},
        {"circulation.allLoanYears", "Toutes les années de prêt"},
        {"members.allAgeGroups", "Toutes les tranches d'âge"},
        {"members.allCities", "Toutes les villes"},
        {"members.noPhoto", "Pas de photo"},
        {"members.hasIdImage", "Oui"},
        {"members.col.number", "Numéro"},
        {"members.col.name", "Nom"},
        {"members.col.phone", "Téléphone"},
        {"members.col.city", "Ville"},
        {"members.col.status", "Statut"},
        {"members.col.loans", "Prêts"},
        {"members.editMember", "Modifier l'adhérent"},
        {"members.deleteMember", "Supprimer l'adhérent"},
        {"members.selectMemberFirst", "Sélectionnez d'abord un adhérent."},
        {"members.deleteConfirm", "Retirer l'adhérent sélectionné ?"},
        {"members.goToLoans", "Aller aux prêts"},
        {"members.deleteBlockedByLoans",
         "Cet adhérent a encore des ouvrages en prêt. Enregistrez leur retour "
                        "avant de le retirer."},
        {"member.status.active", "Actif"},
        {"member.status.non_active", "Inactif"},
        {"member.addTitle", "Ajouter un adhérent"},
        {"member.editTitle", "Modifier l'adhérent"},
        {"member.field.number", "Numéro d'adhésion"},
        {"member.field.numberHint", "Attribué automatiquement, non modifiable"},
        {"member.field.firstName", "Prénom"},
        {"member.field.lastName", "Nom"},
        {"member.field.sex", "Sexe"},
        {"member.sex.male", "Homme"},
        {"member.sex.female", "Femme"},
        {"member.field.occupation", "Profession"},
        {"member.field.ageGroup", "Tranche d'âge"},
        {"member.ageGroup.youth", "Jeunes"},
        {"member.ageGroup.adult", "Adultes"},
        {"member.field.dateOfBirth", "Date de naissance"},
        {"member.field.registeredAt", "Date d'inscription"},
        {"member.field.email", "E-mail"},
        {"member.field.phone", "Téléphone"},
        {"member.field.address", "Adresse"},
        {"member.field.city", "Ville"},
        {"member.field.status", "Statut"},
        {"member.field.activeUntil", "Actif jusqu'au"},
        {"member.field.notes", "Notes"},
        {"member.field.photo", "Photo"},
        {"member.field.idImage", "Pièce d'identité"},
        {"member.choosePhoto", "Choisir une photo…"},
        {"member.chooseIdImage", "Choisir une pièce d'identité…"},
        {"member.selectPhoto", "Sélectionner une photo"},
        {"member.selectIdImage", "Sélectionner une pièce d'identité"},
        {"member.imageFilter", "Images (*.png *.jpg *.jpeg *.webp *.bmp)"},
        {"member.viewPhoto", "Voir la photo"},
        {"member.viewIdImage", "Voir la pièce d'identité"},
        {"imageViewer.change", "Changer…"},
        {"imageViewer.remove", "Retirer"},
        {"imageViewer.close", "Fermer"},
        {"member.validation", "Validation"},
        {"member.nameRequired", "Le prénom et le nom sont obligatoires."},
        {"member.emailInvalid", "Adresse e-mail invalide. Exemple : name@example.org"},
        {"member.dateOfBirthRequired", "Renseignez la date de naissance."},
        {"member.dateOfBirthInvalid",
         "Date de naissance invalide. Utilisez le format AAAA-MM-JJ, par exemple 1990-05-12."},
        {"member.dateOfBirthInFuture",
         "La date de naissance ne peut pas être postérieure à aujourd'hui."},
        {"circulation.searchPlaceholder",
         "Rechercher par adhérent, titre ou exemplaire…"},
        {"circulation.checkout", "Prêter"},
        {"circulation.extend", "Prolonger"},
        {"circulation.return", "Retourner"},
        {"circulation.filter.open", "Ouverts"},
        {"circulation.filter.overdue", "En retard"},
        {"circulation.filter.returned", "Retournés"},
        {"circulation.filter.all", "Tous"},
        {"circulation.col.member", "Adhérent"},
        {"circulation.col.number", "Numéro"},
        {"circulation.col.title", "Titre"},
        {"circulation.col.borrowed", "Prêt"},
        {"circulation.col.due", "Échéance"},
        {"circulation.col.status", "Statut"},
        {"circulation.status.open", "Ouvert"},
        {"circulation.status.overdue", "En retard"},
        {"circulation.status.returned", "Retourné"},
        {"circulation.selectLoanFirst", "Sélectionnez d'abord un prêt."},
        {"circulation.alreadyReturned", "Ce prêt est déjà retourné."},
        {"circulation.delete", "Supprimer"},
        {"circulation.archiveLoan", "Déplacer ce prêt rendu vers les archives ?"},
        {"loan.checkoutTitle", "Prêter un ouvrage"},
        {"loan.returnTitle", "Retourner un ouvrage"},
        {"loan.extendTitle", "Prolonger le prêt"},
        {"loan.returnSummary",
         "{member} ({number}) — {title} [{copy}]"},
        {"loan.field.memberSearch", "Rechercher un adhérent"},
        {"loan.field.member", "Adhérent"},
        {"loan.field.copySearch", "Rechercher un exemplaire"},
        {"loan.field.copy", "Exemplaire"},
        {"loan.field.borrowedAt", "Date de prêt"},
        {"loan.field.dueAt", "Date d'échéance"},
        {"loan.field.currentDueAt", "Date d'échéance actuelle"},
        {"loan.field.newDueAt", "Nouvelle date d'échéance"},
        {"loan.field.returnedAt", "Date de retour"},
        {"loan.field.notes", "Notes"},
        {"loan.memberSearchHint", "Numéro ou nom…"},
        {"loan.copySearchHint", "Titre, exemplaire ou ISBN…"},
        {"loan.noMembers", "(Aucun adhérent actif)"},
        {"loan.noCopies", "(Aucun exemplaire disponible)"},
        {"loan.validation", "Validation"},
        {"loan.memberRequired", "Sélectionnez un adhérent actif."},
        {"loan.copyRequired", "Sélectionnez un exemplaire disponible."},
        {"loan.dueBeforeBorrow",
         "La date d'échéance ne peut pas précéder la date de prêt."},
        {"loan.extendInvalid",
         "La nouvelle date d'échéance doit être postérieure à la date actuelle."},
        {"loan.returnAfterToday",
         "La date de retour ne peut pas être dans le futur."},
        {"catalog.searchPlaceholder",
         "Rechercher par titre, auteur, ISBN ou numéro local…"},
        {"catalog.withCover", "Avec couverture"},
        {"catalog.withoutCover", "Sans couverture"},
        {"catalog.allCovers", "Tous"},
        {"catalog.addBook", "Ajouter un ouvrage"},
        {"catalog.edit", "Modifier"},
        {"catalog.delete", "Supprimer"},
        {"catalog.categories", "Catégories…"},
        {"catalog.loans", "Prêts"},
        {"catalog.loanHistoryTitle", "Historique des prêts — {name}"},
        {"catalog.loanHistoryEmpty", "Cet ouvrage n'a pas encore été prêté."},
        {"catalog.allCategories", "Toutes les catégories"},
        {"catalog.allLanguages", "Toutes les langues"},
        {"catalog.noCover", "Pas de couverture"},
        {"catalog.col.title", "Titre"},
        {"catalog.col.author", "Auteur"},
        {"catalog.col.category", "Catégorie"},
        {"catalog.col.localNumber", "N° local"},
        {"catalog.col.copies", "Exemplaires"},
        {"catalog.col.available", "Disponibles"},
        {"catalog.editBook", "Modifier l'ouvrage"},
        {"catalog.deleteBook", "Supprimer l'ouvrage"},
        {"catalog.selectBookFirst", "Sélectionnez d'abord un ouvrage."},
        {"catalog.deleteConfirm", "Déplacer cet ouvrage et tous ses exemplaires vers les archives ?"},
        {"book.language.ar", "Arabe"},
        {"book.language.fr", "Français"},
        {"book.language.en", "Anglais"},
        {"book.language.es", "Espagnol"},
        {"book.language.de", "Allemand"},
        {"book.language.it", "Italien"},
        {"book.language.tr", "Turc"},
        {"book.language.pt", "Portugais"},
        {"book.language.ru", "Russe"},
        {"book.language.zh", "Chinois"},
        {"book.language.other", "Autre…"},
        {"book.addTitle", "Ajouter un ouvrage"},
        {"book.editTitle", "Modifier l'ouvrage"},
        {"book.field.title", "Titre"},
        {"book.field.author", "Auteur"},
        {"book.field.publisher", "Éditeur"},
        {"book.field.category", "Catégorie"},
        {"book.field.isbn", "ISBN"},
        {"book.field.publicationDate", "Date de publication"},
        {"book.field.publicationDateHint", "ex. 2020 ou 2020-05-12"},
        {"book.field.place", "Lieu de publication"},
        {"book.field.pages", "Pages"},
        {"book.field.dimensions", "Dimensions"},
        {"book.field.language", "Langue"},
        {"book.field.languageOtherHint", "Précisez la langue"},
        {"book.field.cover", "Couverture"},
        {"book.field.description", "Description"},
        {"book.noneCategory", "(aucune)"},
        {"book.tab.book", "Ouvrage"},
        {"book.tab.copies", "Exemplaires"},
        {"book.copy.localId", "N° local"},
        {"book.copy.globalId", "N° global"},
        {"book.copy.source", "Fonds"},
        {"book.copy.source.arabic", "Arabe"},
        {"book.copy.source.foreign", "Étranger"},
        {"book.copy.centralId", "N° central"},
        {"book.copy.classification", "Cote"},
        {"book.copy.subject", "Matière"},
        {"book.copy.indexCode", "Index"},
        {"book.copy.location", "Emplacement"},
        {"book.copy.inventoryStatus", "Inventaire"},
        {"book.copy.compensation", "Compensation"},
        {"book.copy.notes", "Remarques"},
        {"book.copy.status", "État"},
        {"book.copy.statusOnLoan", "Emprunté"},
        {"book.copy.statusAvailable", "Disponible"},
        {"book.copy.add", "Ajouter un exemplaire"},
        {"book.copy.remove", "Supprimer l'exemplaire"},
        {"book.copy.selectFirst",
         "Veuillez d'abord sélectionner un exemplaire."},
        {"book.copy.identifierRequired",
         "Chaque exemplaire a besoin d'un n° local et d'un n° global."},
        {"book.copy.duplicateIdentifier",
         "Le numéro {identifier} est utilisé deux fois dans cette liste."},
        {"book.copy.cannotRemoveOnLoan",
         "Impossible de supprimer un exemplaire actuellement emprunté."},
        {"book.copy.numberReserved", "Ce numéro reste réservé jusqu'à l'enregistrement."},
        {"book.chooseCover", "Choisir une couverture…"},
        {"book.selectCover", "Sélectionner une couverture"},
        {"book.coverFilter", "Images (*.png *.jpg *.jpeg *.webp *.bmp)"},
        {"book.validation", "Validation"},
        {"book.titleRequired", "Le titre est obligatoire."},
        {"book.languageRequired", "La langue est obligatoire."},
        {"ocr.title", "Depuis une image"},
        {"ocr.readFromImage", "Depuis une image"},
        {"ocr.readFromImageTip",
         "Extraire le texte d'une image via Tesseract"},
        {"ocr.languageInUse", "Langue utilisée : {languages}"},
        {"ocr.imageFilter",
         "Images (*.png *.jpg *.jpeg *.webp *.bmp *.tif *.tiff)"},
        {"ocr.selectImage", "Sélectionner une image à lire"},
        {"ocr.working", "Lecture du texte de l'image…"},
        {"ocr.cancelling", "Annulation…"},
        {"ocr.unavailable",
         "Moteur OCR indisponible. Installez libtesseract et les packs de langues."},
        {"ocr.imageMissing", "Impossible d'ouvrir l'image sélectionnée."},
        {"ocr.startFailed", "Impossible de démarrer le moteur OCR."},
        {"ocr.failed", "Échec de la reconnaissance de texte."},
        {"ocr.empty", "Aucun texte détecté dans l'image."},
        {"category.manageTitle", "Gérer les catégories"},
        {"category.col.code", "Code"},
        {"category.col.label", "Libellé"},
        {"category.col.books", "Ouvrages"},
        {"category.add", "Ajouter"},
        {"category.edit", "Modifier"},
        {"category.delete", "Supprimer"},
        {"category.addTitle", "Ajouter une catégorie"},
        {"category.editTitle", "Modifier la catégorie"},
        {"category.deleteTitle", "Supprimer la catégorie"},
        {"category.field.code", "Code :"},
        {"category.field.label", "Libellé :"},
        {"category.selectFirst", "Sélectionnez d'abord une catégorie."},
        {"category.deleteConfirm",
         "Supprimer cette catégorie ? Les catégories contenant des ouvrages ne peuvent "
                        "pas être supprimées."},
        {"copy.note.wasIndexedAs", "était indexé sous {number}"},
        {"copy.note.newIndexedAs", "nouvellement indexé sous {number}"},
        {"error.sql", "Une erreur de base de données s'est produite."},
        {"error.book.notFound", "Cet ouvrage n'existe plus."},
        {"error.book.titleRequired", "Le titre est obligatoire."},
        {"error.book.languageRequired", "La langue est obligatoire."},
        {"error.book.minCopies", "Un ouvrage doit avoir au moins un exemplaire."},
        {"error.book.hasActiveLoans",
         "Impossible de supprimer un ouvrage avec des prêts en cours."},
        {"error.book.hasCopies",
         "Supprimez les exemplaires archivés avant de supprimer définitivement l'ouvrage."},
        {"error.book.duplicateArchived", "Cet ouvrage est dans les archives ; restaurez-le depuis celles-ci."},
        {"error.book.notArchived", "Cet ouvrage n'est pas archivé."},
        {"error.cover.emptyPath", "Le chemin de la couverture est vide."},
        {"error.cover.missingFile", "Fichier de couverture introuvable."},
        {"error.cover.copyFailed", "Échec de la copie de la couverture."},
        {"error.category.codeRequired", "Le code de catégorie est obligatoire."},
        {"error.category.notFound", "Cette catégorie n'existe plus."},
        {"error.category.hasBooks",
         "Impossible de supprimer une catégorie qui contient encore des ouvrages."},
        {"error.copy.nextNumber", "Impossible de déterminer le prochain numéro d'exemplaire."},
        {"error.copy.idsRequired",
         "Chaque exemplaire doit avoir un numéro local et un numéro global."},
        {"error.copy.duplicateGlobalInList",
         "Le numéro d'exemplaire « {detail} » est utilisé deux fois."},
        {"error.copy.duplicateLocalInList",
         "Le numéro local « {detail} » est utilisé deux fois pour le même fonds."},
        {"error.copy.onLoan",
         "Impossible de retirer des exemplaires actuellement en prêt."},
        {"error.copy.duplicateGlobal",
         "Le numéro d'exemplaire « {detail} » appartient déjà à un autre exemplaire."},
        {"error.copy.duplicateLocal",
         "Le numéro local « {detail} » appartient déjà à un autre exemplaire du même fonds."},
        {"error.copy.notFound", "Cet exemplaire n'existe plus."},
        {"error.copy.notArchived", "Cet exemplaire n'est pas archivé."},
        {"error.copy.hasHistory",
         "Cet exemplaire a été emprunté ; supprimez d'abord ses prêts archivés."},
        {"error.copy.bookMissing", "L'ouvrage d'origine de cet exemplaire n'existe plus."},
        {"error.copy.numberHeldByArchived",
         "Le n° « {detail} » est détenu par un exemplaire archivé ; déplacez-le via "
         "Archives → Réutiliser le n° local."},
        {"error.copy.reuseStale", "L'exemplaire archivé ne détient plus ce numéro."},
        {"error.copy.sourceMismatch", "La langue de cet ouvrage ne correspond pas à la source du numéro."},
        {"error.member.notFound", "Cet adhérent n'existe plus."},
        {"error.member.namesRequired", "Le prénom et le nom sont obligatoires."},
        {"error.member.invalidSex", "Sexe d'adhérent invalide."},
        {"error.member.invalidDob",
         "La date de naissance doit être une date réelle au format AAAA-MM-JJ."},
        {"error.member.dobInFuture",
         "La date de naissance ne peut pas être postérieure à aujourd'hui."},
        {"error.member.invalidEmail",
         "L'e-mail doit ressembler à name@example.org, ou rester vide."},
        {"error.member.invalidStatus", "Statut d'adhérent invalide."},
        {"error.member.archiveHasLoans",
         "Impossible d'archiver un adhérent avec des prêts en cours."},
        {"error.member.deleteHasLoans",
         "Impossible de supprimer un adhérent avec des prêts en cours."},
        {"error.member.hasHistory",
         "Cet adhérent a un historique de prêts et ne peut pas être supprimé. Archivez-le plutôt."},
        {"error.member.notArchived", "Cet adhérent n'est pas archivé."},
        {"error.image.emptyPath", "Le chemin de l'image est vide."},
        {"error.image.missingFile", "Fichier image introuvable."},
        {"error.image.copyFailed", "Échec de la copie de l'image."},
        {"error.loan.notFound", "Ce prêt n'existe plus."},
        {"error.loan.alreadyReturned", "Ce prêt est déjà rendu."},
        {"error.loan.dueRequired", "La date d'échéance est obligatoire."},
        {"error.loan.memberRequired", "L'adhérent est obligatoire."},
        {"error.loan.copyRequired", "L'exemplaire est obligatoire."},
        {"error.loan.cannotReturn", "Le prêt n'a pas pu être rendu."},
        {"error.loan.cannotExtend", "Le prêt n'a pas pu être prolongé."},
        {"error.loan.memberArchived",
         "Cet adhérent a été archivé et ne peut pas emprunter."},
        {"error.loan.memberInactive", "Seuls les adhérents actifs peuvent emprunter."},
        {"error.loan.copyNotFound", "Exemplaire introuvable."},
        {"error.loan.copyOnLoan", "Cet exemplaire est déjà en prêt."},
        {"error.loan.borrowUnreadable",
         "La date d'emprunt doit être une date réelle au format AAAA-MM-JJ."},
        {"error.loan.dueUnreadable",
         "La date d'échéance doit être une date réelle au format AAAA-MM-JJ."},
        {"error.loan.dueNotAfterBorrow",
         "La date d'échéance doit être postérieure à la date d'emprunt."},
        {"error.loan.borrowInFuture",
         "La date d'emprunt ne peut pas être dans le futur."},
        {"error.loan.returnUnreadable",
         "La date de retour doit être une date réelle au format AAAA-MM-JJ."},
        {"error.loan.storedBorrowUnreadable",
         "La date d'emprunt de ce prêt est illisible, donc une date de retour ne peut pas être vérifiée. Corrigez d'abord le prêt."},
        {"error.loan.returnBeforeBorrow",
         "La date de retour ne peut pas précéder la date d'emprunt."},
        {"error.loan.returnInFuture",
         "La date de retour ne peut pas être dans le futur."},
        {"error.loan.storedDueUnreadable",
         "La date d'échéance de ce prêt est illisible, donc il ne peut pas être prolongé. Corrigez d'abord le prêt."},
        {"error.loan.extendNotAfter",
         "La nouvelle date d'échéance doit être postérieure à la date actuelle."},
        {"error.loan.extendInPast",
         "La nouvelle date d'échéance ne peut pas être dans le passé."},
        {"error.loan.archiveOpen", "Un prêt non rendu ne peut pas être archivé."},
        {"error.loan.notArchived", "Ce prêt n'est pas archivé."},
        {"error.loan.copyArchived", "Cet exemplaire est archivé et ne peut pas être prêté."},
    };
}

StringTable englishStrings()
{
    return {
        {"app.title", "VLMS — Virtual Library Management System"},
        {"nav.members", "Members"},
        {"nav.catalog", "Catalogue"},
        {"nav.circulation", "Circulation"},
        {"nav.metrics", "Metrics"},
        {"nav.help", "Help"},
        {"help.tooltip", "Open the user manual"},
        {"help.notFound", "The user manual could not be found."},
        {"help.noBrowser", "No browser was found to open the user manual."},
        {"nav.archive", "Archive"},
        {"lang.ar", "العربية"},
        {"lang.fr", "Français"},
        {"lang.en", "English"},
        {"theme.toDark", "Dark mode"},
        {"theme.toLight", "Light mode"},
        {"theme.label", "Interface theme"},
        {"footer.copyright", "© {year} VLMS"},
        {"licence.title", "Licence"},
        {"licence.intro",
         "VLMS is given as a gift to the Library that uses it. Nothing was charged for it, "
         "nothing is owed for it, and the gift cannot be taken back."},
        {"licence.clause.ownership.head", "The solution is the Library's"},
        {"licence.clause.ownership.body",
         "The application, as it is installed here, belongs to the Library that uses it. "
         "The Library may use it, keep it, copy it and pass it on as it sees fit."},
        {"licence.clause.data.head", "The Library's records are its own"},
        {"licence.clause.data.body",
         "The catalogue, the member records, the scans and the photographs the Library "
         "creates with this application belong to the Library alone. The author claims no "
         "right over them and keeps no copy of them."},
        {"licence.clause.warranty.head", "No warranty"},
        {"licence.clause.warranty.body",
         "The application is given as it is. No promise is made that it is free of faults, "
         "that it suits any particular purpose, or that it will keep working. The Library "
         "should keep its own backups of its records."},
        {"licence.clause.liability.head", "No liability"},
        {"licence.clause.liability.body",
         "The author is not responsible for any loss or damage that follows from using this "
         "application, whether the use was mistaken or deliberate. This includes records "
         "lost or corrupted, work interrupted, and anything that follows from either."},
        {"licence.clause.support.head", "No duty to support"},
        {"licence.clause.support.body",
         "The author is under no obligation to provide support, training, updates or "
         "repairs. Any help given is a continuation of the gift, not a duty owed."},
        {"licence.contact.head", "Contact"},
        {"licence.contact.author", "The author: Mohamed Lamine Ben Hassine"},
        {"licence.tooltip", "Show the licence"},
        {"common.error", "Error"},
        {"common.cancel", "Cancel"},
        {"common.ok", "OK"},
        {"common.yes", "Yes"},
        {"common.no", "No"},
        {"common.close", "Close"},
        {"file.open", "Open"},
        {"file.fileName", "File name:"},
        {"file.fileType", "File type:"},
        {"file.lookIn", "Look in:"},
        {"app.databaseUnavailable",
         "The database could not be opened. It may have been created by a newer "
                        "version of this program. Update VLMS or contact your "
                        "administrator."},
        {"common.emDash", "—"},
        {"pager.previous", "Previous"},
        {"pager.next", "Next"},
        {"pager.first", "First"},
        {"pager.last", "Last"},
        {"pager.all", "ALL"},
        {"pager.range", "{from}–{to} of {total}"},
        {"pager.page", "page"},
        {"page.members.title", "Members"},
        {"page.members.body", "Register members, manage photos and ID images, update contact data, change status (active, not active), add notes, and handle loans and returns."},
        {"page.catalog.title", "Catalogue"},
        {"page.catalog.body",
         "Add and edit books, manage categories, attach cover images, and remove titles."},
        {"page.circulation.title", "Circulation"},
        {"page.circulation.body",
         "Issue books to members and process returns at the desk."},
        {"page.metrics.title", "Metrics"},
        {"page.metrics.body",
         "View library traffic and activity: daily, weekly, and monthly summaries."},
        {"page.archive.title", "Archive"},
        {"page.archive.body", "Archived members, books, copies, and loans."},
        {"archive.type.members", "Members"},
        {"archive.type.books", "Books"},
        {"archive.type.copies", "Copies"},
        {"archive.type.loans", "Loans"},
        {"archive.searchPlaceholder", "Search the archive…"},
        {"archive.col.number", "Number"},
        {"archive.col.name", "Name"},
        {"archive.col.city", "City"},
        {"archive.col.status", "Status"},
        {"archive.col.title", "Title"},
        {"archive.col.author", "Author"},
        {"archive.col.copies", "Archived copies"},
        {"archive.col.localId", "Local no."},
        {"archive.col.source", "Source"},
        {"archive.col.member", "Member"},
        {"archive.col.copy", "Copy / title"},
        {"archive.col.returnedAt", "Returned"},
        {"archive.col.archivedAt", "Archived"},
        {"archive.col.notes", "Copy notes"},
        {"archive.col.loans", "Loans"},
        {"archive.restore", "Restore"},
        {"archive.restoreConfirm", "Restore this record from the Archive?"},
        {"archive.purge", "Permanently remove"},
        {"archive.purgeConfirmMember",
         "Permanently remove this member? This cannot be undone."},
        {"archive.purgeConfirmBook",
         "Permanently remove this title? This cannot be undone."},
        {"archive.purgeConfirmCopy",
         "Permanently remove this copy? Its local number becomes free again. "
         "This cannot be undone."},
        {"archive.purgeConfirmLoan",
         "Permanently remove this loan? This cannot be undone."},
        {"bulk.confirm", "{verb} {count} {noun}?"},
        {"bulk.confirmOne", "{verb} “{label}”?"},
        {"bulk.blockedIntro", "{blocked} of {count} {noun} can't be {passive}:"},
        {"bulk.andMore", "…and {count} more"},
        {"bulk.confirmRest", "{verb} the other {count}?"},
        {"bulk.summary", "{done} {passive}, {failed} failed: {reason}"},
        {"bulk.noun.books", "books"},
        {"bulk.noun.members", "members"},
        {"bulk.noun.loans", "loans"},
        {"bulk.noun.copies", "copies"},
        {"bulk.verb.archive", "Archive"},
        {"bulk.passive.archive", "archived"},
        {"bulk.verb.restore", "Restore"},
        {"bulk.passive.restore", "restored"},
        {"bulk.verb.purge", "Permanently remove"},
        {"bulk.passive.purge", "removed"},
        {"bulk.verb.remove", "Remove"},
        {"bulk.passive.remove", "removed"},
        {"archive.loans", "Loans"},
        {"archive.loanHistoryTitle", "Loan history — {name}"},
        {"archive.loanHistoryEmpty", "No loans."},
        {"archive.reuse", "Reuse local number"},
        {"archive.reuse.title", "Choose the book"},
        {"archive.reuse.prompt", "Book that takes number {number}:"},
        {"archive.reuse.search", "Search for a book…"},
        {"archive.reuse.newBook", "New book"},
        {"metrics.refresh", "Refresh"},
        {"metrics.section.overview", "Library overview"},
        {"metrics.section.members", "Members"},
        {"metrics.section.circulation", "Circulation"},
        {"metrics.section.activity", "Activity"},
        {"metrics.section.categories", "Top categories"},
        {"metrics.bookTitles", "Book titles"},
        {"metrics.totalCopies", "Total copies"},
        {"metrics.availableCopies", "Available copies"},
        {"metrics.onLoanCopies", "Copies on loan"},
        {"metrics.totalMembers", "Total members"},
        {"metrics.membersActive", "Active"},
        {"metrics.membersNonActive", "Not active"},
        {"metrics.openLoans", "Open loans"},
        {"metrics.overdueLoans", "Overdue loans"},
        {"metrics.returnedLoans", "Returned loans"},
        {"metrics.period.today", "Today"},
        {"metrics.period.week", "Last 7 days"},
        {"metrics.period.month", "This month"},
        {"metrics.col.period", "Period"},
        {"metrics.col.checkouts", "Checkouts"},
        {"metrics.col.returns", "Returns"},
        {"metrics.col.newMembers", "New members"},
        {"metrics.col.category", "Category"},
        {"metrics.col.books", "Books"},
        {"metrics.noCategories", "No categories yet."},
        {"members.searchPlaceholder",
         "Search by number, name, phone, or city…"},
        {"members.addMember", "Add Member"},
        {"members.loans", "Loans"},
        {"members.loanHistoryTitle", "Loan history — {name}"},
        {"members.loanHistoryEmpty", "This member has not borrowed anything yet."},
        {"members.edit", "Edit"},
        {"members.delete", "Delete"},
        {"members.allStatuses", "All statuses"},
        {"members.allSexes", "All sexes"},
        {"members.allYears", "All years"},
        {"circulation.allLoanYears", "All loan years"},
        {"members.allAgeGroups", "All age groups"},
        {"members.allCities", "All cities"},
        {"members.noPhoto", "No photo"},
        {"members.hasIdImage", "Yes"},
        {"members.col.number", "Number"},
        {"members.col.name", "Name"},
        {"members.col.phone", "Phone"},
        {"members.col.city", "City"},
        {"members.col.status", "Status"},
        {"members.col.loans", "Loans"},
        {"members.editMember", "Edit Member"},
        {"members.deleteMember", "Delete Member"},
        {"members.selectMemberFirst", "Select a member first."},
        {"members.deleteConfirm", "Remove the selected member?"},
        {"members.goToLoans", "Go to Loans"},
        {"members.deleteBlockedByLoans",
         "This member still has books on loan. Return them first, then remove "
                        "the member."},
        {"member.status.active", "Active"},
        {"member.status.non_active", "Not active"},
        {"member.addTitle", "Add Member"},
        {"member.editTitle", "Edit Member"},
        {"member.field.number", "Membership number"},
        {"member.field.numberHint", "Assigned automatically and cannot be changed"},
        {"member.field.firstName", "First name"},
        {"member.field.lastName", "Last name"},
        {"member.field.sex", "Sex"},
        {"member.sex.male", "Male"},
        {"member.sex.female", "Female"},
        {"member.field.occupation", "Occupation"},
        {"member.field.ageGroup", "Age group"},
        {"member.ageGroup.youth", "Youth"},
        {"member.ageGroup.adult", "Adults"},
        {"member.field.dateOfBirth", "Date of birth"},
        {"member.field.registeredAt", "Registered"},
        {"member.field.email", "Email"},
        {"member.field.phone", "Phone"},
        {"member.field.address", "Address"},
        {"member.field.city", "City"},
        {"member.field.status", "Status"},
        {"member.field.activeUntil", "Active until"},
        {"member.field.notes", "Notes"},
        {"member.field.photo", "Photo"},
        {"member.field.idImage", "ID image"},
        {"member.choosePhoto", "Choose photo…"},
        {"member.chooseIdImage", "Choose ID image…"},
        {"member.selectPhoto", "Select member photo"},
        {"member.selectIdImage", "Select ID image"},
        {"member.imageFilter", "Images (*.png *.jpg *.jpeg *.webp *.bmp)"},
        {"member.viewPhoto", "View photo"},
        {"member.viewIdImage", "View ID image"},
        {"imageViewer.change", "Change…"},
        {"imageViewer.remove", "Remove"},
        {"imageViewer.close", "Close"},
        {"member.validation", "Validation"},
        {"member.nameRequired", "First name and last name are required."},
        {"member.emailInvalid", "That email address is not valid. Example: name@example.org"},
        {"member.dateOfBirthRequired", "Fill in the date of birth."},
        {"member.dateOfBirthInvalid",
         "That date of birth is not valid. Use the YYYY-MM-DD form, for example 1990-05-12."},
        {"member.dateOfBirthInFuture", "The date of birth cannot be later than today."},
        {"circulation.searchPlaceholder",
         "Search by member, title, or copy…"},
        {"circulation.checkout", "Checkout"},
        {"circulation.extend", "Extend"},
        {"circulation.return", "Return"},
        {"circulation.filter.open", "Open"},
        {"circulation.filter.overdue", "Overdue"},
        {"circulation.filter.returned", "Returned"},
        {"circulation.filter.all", "All"},
        {"circulation.col.member", "Member"},
        {"circulation.col.number", "Number"},
        {"circulation.col.title", "Title"},
        {"circulation.col.borrowed", "Borrowed"},
        {"circulation.col.due", "Due"},
        {"circulation.col.status", "Status"},
        {"circulation.status.open", "Open"},
        {"circulation.status.overdue", "Overdue"},
        {"circulation.status.returned", "Returned"},
        {"circulation.selectLoanFirst", "Select a loan first."},
        {"circulation.alreadyReturned", "This loan is already returned."},
        {"circulation.delete", "Delete"},
        {"circulation.archiveLoan", "Move this returned loan to the Archive?"},
        {"loan.checkoutTitle", "Checkout Book"},
        {"loan.returnTitle", "Return Book"},
        {"loan.extendTitle", "Extend Loan"},
        {"loan.returnSummary",
         "{member} ({number}) — {title} [{copy}]"},
        {"loan.field.memberSearch", "Search member"},
        {"loan.field.member", "Member"},
        {"loan.field.copySearch", "Search copy"},
        {"loan.field.copy", "Copy"},
        {"loan.field.borrowedAt", "Borrowed date"},
        {"loan.field.dueAt", "Due date"},
        {"loan.field.currentDueAt", "Current due date"},
        {"loan.field.newDueAt", "New due date"},
        {"loan.field.returnedAt", "Return date"},
        {"loan.field.notes", "Notes"},
        {"loan.memberSearchHint", "Membership number or name…"},
        {"loan.copySearchHint", "Title, copy code, or ISBN…"},
        {"loan.noMembers", "(No active members)"},
        {"loan.noCopies", "(No available copies)"},
        {"loan.validation", "Validation"},
        {"loan.memberRequired", "Select an active member."},
        {"loan.copyRequired", "Select an available copy."},
        {"loan.dueBeforeBorrow",
         "Due date cannot be before the borrow date."},
        {"loan.extendInvalid",
         "The new due date must be after the current due date."},
        {"loan.returnAfterToday",
         "Return date cannot be in the future."},
        {"catalog.searchPlaceholder",
         "Search by title, author, ISBN, or local number…"},
        {"catalog.withCover", "With cover"},
        {"catalog.withoutCover", "Without cover"},
        {"catalog.allCovers", "All"},
        {"catalog.addBook", "Add Book"},
        {"catalog.edit", "Edit"},
        {"catalog.delete", "Delete"},
        {"catalog.categories", "Categories…"},
        {"catalog.loans", "Loans"},
        {"catalog.loanHistoryTitle", "Loan history — {name}"},
        {"catalog.loanHistoryEmpty", "This book has not been circulated yet."},
        {"catalog.allCategories", "All categories"},
        {"catalog.allLanguages", "All languages"},
        {"catalog.noCover", "No cover"},
        {"catalog.col.title", "Title"},
        {"catalog.col.author", "Author"},
        {"catalog.col.category", "Category"},
        {"catalog.col.localNumber", "Local no."},
        {"catalog.col.copies", "Copies"},
        {"catalog.col.available", "Available"},
        {"catalog.editBook", "Edit Book"},
        {"catalog.deleteBook", "Delete Book"},
        {"catalog.selectBookFirst", "Select a book first."},
        {"catalog.deleteConfirm", "Move this book and all its copies to the Archive?"},
        {"book.language.ar", "Arabic"},
        {"book.language.fr", "French"},
        {"book.language.en", "English"},
        {"book.language.es", "Spanish"},
        {"book.language.de", "German"},
        {"book.language.it", "Italian"},
        {"book.language.tr", "Turkish"},
        {"book.language.pt", "Portuguese"},
        {"book.language.ru", "Russian"},
        {"book.language.zh", "Chinese"},
        {"book.language.other", "Other…"},
        {"book.addTitle", "Add Book"},
        {"book.editTitle", "Edit Book"},
        {"book.field.title", "Title"},
        {"book.field.author", "Author"},
        {"book.field.publisher", "Publisher"},
        {"book.field.category", "Category"},
        {"book.field.isbn", "ISBN"},
        {"book.field.publicationDate", "Publication date"},
        {"book.field.publicationDateHint", "e.g. 2020 or 2020-05-12"},
        {"book.field.place", "Place of publication"},
        {"book.field.pages", "Pages"},
        {"book.field.dimensions", "Dimensions"},
        {"book.field.language", "Language"},
        {"book.field.languageOtherHint", "Specify language"},
        {"book.field.cover", "Cover"},
        {"book.field.description", "Description"},
        {"book.noneCategory", "(none)"},
        {"book.tab.book", "Book"},
        {"book.tab.copies", "Copies"},
        {"book.copy.localId", "Local no."},
        {"book.copy.globalId", "Global no."},
        {"book.copy.source", "Stock"},
        {"book.copy.source.arabic", "Arabic"},
        {"book.copy.source.foreign", "Foreign"},
        {"book.copy.centralId", "Central no."},
        {"book.copy.classification", "Classification"},
        {"book.copy.subject", "Subject"},
        {"book.copy.indexCode", "Index"},
        {"book.copy.location", "Location"},
        {"book.copy.inventoryStatus", "Inventory"},
        {"book.copy.compensation", "Compensation"},
        {"book.copy.notes", "Notes"},
        {"book.copy.status", "Status"},
        {"book.copy.statusOnLoan", "On loan"},
        {"book.copy.statusAvailable", "Available"},
        {"book.copy.add", "Add copy"},
        {"book.copy.remove", "Remove copy"},
        {"book.copy.selectFirst", "Select a copy first."},
        {"book.copy.identifierRequired",
         "Every copy needs a local number and a global number."},
        {"book.copy.duplicateIdentifier",
         "Number {identifier} is used twice in this list."},
        {"book.copy.cannotRemoveOnLoan",
         "Cannot remove a copy that is currently on loan."},
        {"book.copy.numberReserved", "This number stays reserved until the book is saved."},
        {"book.chooseCover", "Choose cover image…"},
        {"book.selectCover", "Select cover image"},
        {"book.coverFilter", "Images (*.png *.jpg *.jpeg *.webp *.bmp)"},
        {"book.validation", "Validation"},
        {"book.titleRequired", "Title is required."},
        {"book.languageRequired", "Language is required."},
        {"ocr.title", "From image"},
        {"ocr.readFromImage", "From image"},
        {"ocr.readFromImageTip",
         "Extract text from an image with Tesseract"},
        {"ocr.languageInUse", "Language in use: {languages}"},
        {"ocr.imageFilter",
         "Images (*.png *.jpg *.jpeg *.webp *.bmp *.tif *.tiff)"},
        {"ocr.selectImage", "Select image to read"},
        {"ocr.working", "Reading text from the image…"},
        {"ocr.cancelling", "Cancelling…"},
        {"ocr.unavailable",
         "OCR engine is unavailable. Install libtesseract and language packs."},
        {"ocr.imageMissing", "Could not open the selected image."},
        {"ocr.startFailed", "Could not start the OCR engine."},
        {"ocr.failed", "Text recognition failed."},
        {"ocr.empty", "No text was found in the image."},
        {"category.manageTitle", "Manage Categories"},
        {"category.col.code", "Code"},
        {"category.col.label", "Label"},
        {"category.col.books", "Books"},
        {"category.add", "Add"},
        {"category.edit", "Edit"},
        {"category.delete", "Delete"},
        {"category.addTitle", "Add Category"},
        {"category.editTitle", "Edit Category"},
        {"category.deleteTitle", "Delete Category"},
        {"category.field.code", "Code:"},
        {"category.field.label", "Label:"},
        {"category.selectFirst", "Select a category first."},
        {"category.deleteConfirm",
         "Delete this category? Categories with books cannot be removed."},
        {"copy.note.wasIndexedAs", "was indexed as {number}"},
        {"copy.note.newIndexedAs", "new indexed as {number}"},
        {"error.sql", "A database error occurred."},
        {"error.book.notFound", "That book no longer exists."},
        {"error.book.titleRequired", "Title is required."},
        {"error.book.languageRequired", "Language is required."},
        {"error.book.minCopies", "A book needs at least one copy."},
        {"error.book.hasActiveLoans", "Cannot delete a book with active loans."},
        {"error.book.hasCopies",
         "Remove this title's archived copies before removing the title itself."},
        {"error.book.duplicateArchived", "This book is in the Archive; restore it from there."},
        {"error.book.notArchived", "This book is not in the Archive."},
        {"error.cover.emptyPath", "Cover image path is empty."},
        {"error.cover.missingFile", "Cover image file not found."},
        {"error.cover.copyFailed", "Failed to copy cover image."},
        {"error.category.codeRequired", "Category code is required."},
        {"error.category.notFound", "That category no longer exists."},
        {"error.category.hasBooks", "Cannot delete a category that still has books."},
        {"error.copy.nextNumber", "Could not work out the next copy number."},
        {"error.copy.idsRequired",
         "Every copy needs a local number and a global number."},
        {"error.copy.duplicateGlobalInList",
         "Copy number '{detail}' is used twice."},
        {"error.copy.duplicateLocalInList",
         "Local number '{detail}' is used twice for the same stock."},
        {"error.copy.onLoan", "Cannot remove copies that are currently on loan."},
        {"error.copy.duplicateGlobal",
         "Copy number '{detail}' already belongs to another copy."},
        {"error.copy.duplicateLocal",
         "Local number '{detail}' already belongs to another copy in the same stock."},
        {"error.copy.notFound", "That copy no longer exists."},
        {"error.copy.notArchived", "This copy is not in the Archive."},
        {"error.copy.hasHistory",
         "This copy has been borrowed; remove its archived loans first."},
        {"error.copy.bookMissing", "This copy's original book no longer exists."},
        {"error.copy.numberHeldByArchived",
         "Number \"{detail}\" is held by an archived copy; move it with Archive → Reuse local number."},
        {"error.copy.reuseStale", "The archived copy no longer holds that number."},
        {"error.copy.sourceMismatch", "This book's language does not match the number's source."},
        {"error.member.notFound", "That member no longer exists."},
        {"error.member.namesRequired", "First name and last name are required."},
        {"error.member.invalidSex", "Invalid member sex."},
        {"error.member.invalidDob",
         "Date of birth must be a real date in YYYY-MM-DD form."},
        {"error.member.dobInFuture", "Date of birth cannot be later than today."},
        {"error.member.invalidEmail",
         "Email must look like name@example.org, or be left empty."},
        {"error.member.invalidStatus", "Invalid member status."},
        {"error.member.archiveHasLoans", "Cannot archive a member with active loans."},
        {"error.member.deleteHasLoans", "Cannot delete a member with active loans."},
        {"error.member.hasHistory",
         "This member has borrowing history and cannot be deleted. Archive them instead."},
        {"error.member.notArchived", "This member is not in the Archive."},
        {"error.image.emptyPath", "Image path is empty."},
        {"error.image.missingFile", "Image file not found."},
        {"error.image.copyFailed", "Failed to copy image."},
        {"error.loan.notFound", "That loan no longer exists."},
        {"error.loan.alreadyReturned", "This loan is already returned."},
        {"error.loan.dueRequired", "Due date is required."},
        {"error.loan.memberRequired", "Member is required."},
        {"error.loan.copyRequired", "Book copy is required."},
        {"error.loan.cannotReturn", "Loan could not be returned."},
        {"error.loan.cannotExtend", "Loan could not be extended."},
        {"error.loan.memberArchived",
         "This member has been archived and cannot borrow."},
        {"error.loan.memberInactive", "Only active members may borrow."},
        {"error.loan.copyNotFound", "Book copy not found."},
        {"error.loan.copyOnLoan", "This copy is already on loan."},
        {"error.loan.borrowUnreadable",
         "Borrow date must be a real date in YYYY-MM-DD form."},
        {"error.loan.dueUnreadable",
         "Due date must be a real date in YYYY-MM-DD form."},
        {"error.loan.dueNotAfterBorrow",
         "Due date must be after the borrow date."},
        {"error.loan.borrowInFuture", "Borrow date cannot be in the future."},
        {"error.loan.returnUnreadable",
         "Return date must be a real date in YYYY-MM-DD form."},
        {"error.loan.storedBorrowUnreadable",
         "This loan's borrow date cannot be read, so a return date cannot be checked "
                        "against it. Correct the loan first."},
        {"error.loan.returnBeforeBorrow",
         "Return date cannot be before the borrow date."},
        {"error.loan.returnInFuture", "Return date cannot be in the future."},
        {"error.loan.storedDueUnreadable",
         "This loan's due date cannot be read, so it cannot be extended. Correct the "
                        "loan first."},
        {"error.loan.extendNotAfter",
         "New due date must be after the current due date."},
        {"error.loan.extendInPast", "New due date cannot be in the past."},
        {"error.loan.archiveOpen", "A loan that has not been returned cannot be archived."},
        {"error.loan.notArchived", "This loan is not in the Archive."},
        {"error.loan.copyArchived", "This copy is archived and cannot be lent."},
    };
}

const StringTable& tableForLocale(std::string_view localeCode)
{
    static const StringTable arabic = arabicStrings();
    static const StringTable french = frenchStrings();
    static const StringTable english = englishStrings();

    if (localeCode == "fr") {
        return french;
    }
    if (localeCode == "en") {
        return english;
    }
    return arabic;
}

std::string tableValue(const StringTable& table, std::string_view key)
{
    const auto it = table.find(std::string(key));
    return it == table.end() ? std::string() : it->second;
}

}  // namespace

std::string Strings::t(std::string_view key, std::string_view param, std::string_view value)
{
    std::string text = lookup(key);
    if (!param.empty()) {
        replaceAll(text, "{" + std::string(param) + "}", std::string(value));
    }
    return text;
}

std::string Strings::t2(std::string_view key,
                        std::string_view p1,
                        std::string_view v1,
                        std::string_view p2,
                        std::string_view v2)
{
    std::string text = lookup(key);
    replaceAll(text, "{" + std::string(p1) + "}", std::string(v1));
    replaceAll(text, "{" + std::string(p2) + "}", std::string(v2));
    return text;
}

std::vector<std::string> Strings::knownKeys(std::string_view localeCode)
{
    const StringTable& table = tableForLocale(localeCode);
    std::vector<std::string> keys;
    keys.reserve(table.size());
    for (const auto& [key, value] : table) {
        keys.push_back(key);
    }
    std::sort(keys.begin(), keys.end());
    return keys;
}

std::string Strings::rawValue(std::string_view localeCode, std::string_view key)
{
    return tableValue(tableForLocale(localeCode), key);
}

std::string Strings::lookup(std::string_view key)
{
    const std::string value = tableValue(tableForLocale(Locale::code()), key);
    if (!value.empty()) {
        return value;
    }
    const std::string fallback = tableValue(tableForLocale(Locale::kDefaultCode), key);
    return fallback.empty() ? std::string(key) : fallback;
}

std::string Strings::bookLanguageLabel(std::string_view code)
{
    const std::string trimmed = trim(code);
    if (trimmed.empty()) {
        return trimmed;
    }
    const std::string key = "book.language." + trimmed;
    const std::string label = lookup(key);
    return label != key ? label : trimmed;
}

std::string Strings::memberStatusLabel(std::string_view code)
{
    const std::string trimmed = trim(code);
    if (trimmed.empty()) {
        return trimmed;
    }
    const std::string key = "member.status." + trimmed;
    const std::string label = lookup(key);
    return label != key ? label : trimmed;
}

std::string Strings::memberSexLabel(std::string_view code)
{
    const std::string trimmed = trim(code);
    if (trimmed.empty()) {
        return trimmed;
    }
    const std::string key = "member.sex." + trimmed;
    const std::string label = lookup(key);
    return label != key ? label : trimmed;
}

std::string Strings::memberAgeGroupLabel(std::string_view code)
{
    const std::string trimmed = trim(code);
    if (trimmed.empty()) {
        return trimmed;
    }
    const std::string key = "member.ageGroup." + trimmed;
    const std::string label = lookup(key);
    return label != key ? label : trimmed;
}

}  // namespace VLMS::Core

